Repository juanxavier357/backend-top-v29-hoteles, pull requests merged in 2023-07, with the labels that each got.

#58 feat: upload image
  package-lock.json
  package.json
  src/api/upload/index.ts
  src/api/upload/upload.controler.ts
  src/api/upload/upload.service.ts
  src/api/user/index.ts
  src/routes.ts
Labels: medium, waiting-for-review

#60 feat: 🎇 verify login
  package-lock.json
  package.json
  src/api/hotel/hotel.seeder.ts
  src/api/user/user.controller.ts
  src/api/user/user.service.ts
  src/auth/local/index.ts
  src/auth/local/local.controller.ts
  src/auth/utils/bcrypt.ts
  src/auth/utils/email.ts
Labels: medium, waiting-for-review

#61 update: ❇️ branch develop in to branch main
  .github/pull_request_template .md
  package-lock.json
  package.json
  src/api/hotel/hotel.seeder.ts
  src/api/upload/index.ts
  src/api/upload/upload.controler.ts
  src/api/upload/upload.service.ts
  src/api/user/index.ts
  src/api/user/user.controller.ts
  src/api/user/user.service.ts
  src/auth/local/index.ts
  src/auth/local/local.controller.ts
  src/auth/utils/bcrypt.ts
  src/auth/utils/email.ts
  src/routes.ts
Labels: large, waiting-for-review

#62 feat: update user.service.ts
  src/api/user/user.service.ts
Labels: small, waiting-for-review

#63 feat 🎇:ci config
  .eslintrc.cjs
  .github/workflows/ci.yml
  package-lock.json
  package.json
Labels: medium, waiting-for-review

#64 Feat/sendgrid
  package.json
  prisma/migrations/20230626194811_add_db_hotels/migration.sql
  prisma/migrations/20230702231257_db_update/migration.sql
  src/api/contactInfo/contactInfo.service.test.ts
  src/api/user/user.controller.ts
  src/api/user/user.service.ts
  src/auth/utils/email.ts
  src/config/express.ts
Labels: medium, waiting-for-review

#68 feat: ❇️ test controllers integrated and working
  package-lock.json
  package.json
  src/api/hotel/hotel.controller.test.ts
  src/api/user/index.ts
  src/api/user/user.controller.ts
  src/api/user/user.service.ts
  src/auth/local/local.controller.ts
  src/auth/utils/email.ts
Labels: small, waiting-for-review

#75 feat: ♠️ corrections de code error in api user controller
  src/api/user/user.controller.ts
Labels: small, waiting-for-review

#77 feat: :sparkles: upload cloudinary images for hotels
  .github/workflows/ci.yml
  package.json
  src/api/image/image.seeder.ts
Labels: medium, waiting-for-review

#79 Feat/stripe config
  package-lock.json
  package.json
  prisma/migrations/20230712212828_db_edit/migration.sql
  prisma/schema.prisma
  src/api/payment/index.ts
  src/api/payment/payment.controller.ts
  src/api/payment/payment.service.ts
  src/api/payment/payment.types.ts
  src/routes.ts
Labels: medium, waiting-for-review

#80 update schema model payments
  .github/workflows/ci.yml
  package-lock.json
  package.json
  prisma/migrations/20230712212828_db_edit/migration.sql
  prisma/schema.prisma
  src/api/image/image.seeder.ts
  src/api/payment/index.ts
  src/api/payment/payment.controller.ts
  src/api/payment/payment.service.ts
  src/api/payment/payment.types.ts
  src/routes.ts
Labels: large, waiting-for-review

#81 feat: bug fix
  src/auth/local/local.controller.ts
Labels: small, waiting-for-review
