Repository juanxavier357/backend-top-v29-hoteles, pull requests merged in 2023-06, with the labels that each got.

#2 Feature/database
  .editorconfig
  .eslintrc.cjs
  .husky/commit-msg
  .prettierrc
  LICENSE
  commitlint.config.cjs
  package-lock.json
  package.json
  reviewpad.yml
  tsconfig.json
Labels: enhancement

#22 Feature/add seed
  prisma/migrations/20230621224511_add_hotel_booking/migration.sql
  prisma/schema.prisma
  src/api/amenity/index.ts
  src/api/contactInfo/contactInfo.controller.ts
  src/api/contactInfo/contactInfo.service.ts
  src/api/contactInfo/contactInfo.types.ts
  src/api/contactInfo/index.ts
Labels: large, waiting-for-review

#24 feat: :sparkles: add has role middleware and some files moved
  prisma/schema.prisma
  src/api/user/index.ts
  src/api/user/user.controller.ts
  src/api/user/user.service.ts
  src/auth/auth.controller.ts
  src/auth/auth.service.ts
  src/auth/auth.types.ts
  src/auth/local/index.ts
  src/auth/local/local.controller.ts
Labels: medium, waiting-for-review

#28 Update Main from Develop
  .github/pull_request_template .md
  prisma/migrations/20230609230748_add_dbhotels/migration.sql
Labels: medium, waiting-for-review

#31 Cambios
  src/api/user/index.ts
  src/api/user/user.service.ts
  src/auth/local/local.controller.ts
Labels: small, waiting-for-review

#34 Feature/seeder location
  prisma/seed.ts
  src/api/location/location.seeder.ts
Labels: medium, waiting-for-review

#36 Feature/seeder contact info
  prisma/seed.ts
  src/api/contactInfo/contactInfo.seeder.ts
  src/api/image/image.seeder.ts
Labels: large, waiting-for-review

#39 borrar dist
  dist/api/amenity/amenity.controller.js
  dist/api/amenity/amenity.service.js
  dist/api/amenity/amenity.types.js
  dist/api/amenity/index.js
  dist/api/contactInfo/contactInfo.controller.js
  dist/api/contactInfo/contactInfo.service.js
  dist/api/contactInfo/contactInfo.types.js
  dist/api/contactInfo/index.js
  dist/api/facility/facility.controller.js
  dist/api/facility/facility.service.js
  dist/api/facility/facility.types.js
  dist/api/facility/index.js
  dist/api/hotel/hotel.controller.js
  dist/api/hotel/hotel.seeder.js
  dist/api/hotel/hotel.service.js
  dist/api/hotel/hotel.types.js
  dist/api/hotel/index.js
  dist/api/image/image.controller.js
  dist/api/image/image.service.js
  dist/api/image/image.types.js
  dist/api/image/index.js
  dist/api/location/index.js
  dist/api/location/location.controller.js
  dist/api/location/location.service.js
  dist/api/location/location.types.js
  dist/api/reservation/index.js
  dist/api/reservation/reservation.controller.js
  dist/api/reservation/reservation.service.js
  dist/api/reservation/reservation.types.js
  dist/api/role/index.js
  dist/api/role/role.controller.js
  dist/api/role/role.seeder.js
  dist/api/role/role.service.js
  dist/api/role/role.types.js
  dist/api/room/index.js
  dist/api/room/room.controller.js
  dist/api/room/room.service.js
  dist/api/room/room.types.js
  dist/api/user/index.js
  dist/api/user/user.controller.js
  dist/api/user/user.seeder.js
  dist/api/user/user.service.js
  dist/api/user/user.types.js
  dist/auth/auth.service.js
  dist/auth/local/index.js
  dist/auth/local/local.controller.js
  dist/auth/utils/bcrypt.js
  dist/config/express.js
  dist/index.js
  dist/routes.js
Labels: large, waiting-for-review

#41 Feat/testingrole
  src/api/role/role.service.test.ts
Labels: small, waiting-for-review

#42 Feature/test api
  src/api/contactInfo/contactInfo.controller.test.ts
  src/api/contactInfo/contactInfo.seeder.ts
  src/api/image/image.controller.test.ts
  src/api/user/user.controller.test.ts
Labels: medium, waiting-for-review

#43 User service test
  src/api/user/user.service.test.ts
Labels: small, waiting-for-review

#49 feat: add hotel test
  src/api/contactInfo/contactInfo.controller.test.ts
  src/api/hotel/hotel.controller.test.ts
  src/api/hotel/hotel.controller.ts
  src/api/image/image.controller.test.ts
  src/api/location/location.controller.test.ts
Labels: small, waiting-for-review

#50 feat: 🎇 schema update and corrections
  prisma/migrations/20230627214356_update_db/migration.sql
  prisma/schema.prisma
  src/api/hotel/hotel.service.ts
  src/api/location/location.controller.test.ts
  src/api/location/location.seeder.ts
  src/api/user/index.ts
  src/api/user/user.controller.ts
  src/api/user/user.seeder.ts
  src/api/user/user.service.ts
  src/auth/utils/bcrypt.ts
Labels: medium, waiting-for-review

#51 feature: ❇️ update api hotel
  src/api/hotel/hotel.service.ts
Labels: small, waiting-for-review

#53 feat: :sparkles: add include and select
  src/api/hotel/hotel.service.ts
Labels: small, waiting-for-review

#54 feat: :sparkles: update schema
  coverage/clover.xml
  coverage/coverage-final.json
  coverage/lcov-report/base.css
  coverage/lcov-report/block-navigation.js
  coverage/lcov-report/favicon.png
  coverage/lcov-report/index.html
  coverage/lcov-report/prettify.css
  coverage/lcov-report/prettify.js
  coverage/lcov-report/sort-arrow-sprite.png
  coverage/lcov-report/sorter.js
  coverage/lcov-report/src/api/amenity/amenity.controller.ts.html
  coverage/lcov-report/src/api/amenity/amenity.service.ts.html
  coverage/lcov-report/src/api/amenity/index.html
  coverage/lcov-report/src/api/amenity/index.ts.html
  coverage/lcov-report/src/api/contactInfo/contactInfo.controller.ts.html
  coverage/lcov-report/src/api/contactInfo/contactInfo.service.ts.html
  coverage/lcov-report/src/api/contactInfo/index.html
  coverage/lcov-report/src/api/contactInfo/index.ts.html
  coverage/lcov-report/src/api/facility/facility.controller.ts.html
  coverage/lcov-report/src/api/facility/facility.service.ts.html
  coverage/lcov-report/src/api/facility/index.html
  coverage/lcov-report/src/api/facility/index.ts.html
  coverage/lcov-report/src/api/hotel/hotel.controller.ts.html
  coverage/lcov-report/src/api/hotel/hotel.service.ts.html
  coverage/lcov-report/src/api/hotel/index.html
  coverage/lcov-report/src/api/hotel/index.ts.html
  coverage/lcov-report/src/api/image/image.controller.ts.html
  coverage/lcov-report/src/api/image/image.service.ts.html
  coverage/lcov-report/src/api/image/index.html
  coverage/lcov-report/src/api/image/index.ts.html
  coverage/lcov-report/src/api/location/index.html
  coverage/lcov-report/src/api/location/index.ts.html
  coverage/lcov-report/src/api/location/location.controller.ts.html
  coverage/lcov-report/src/api/location/location.service.ts.html
  coverage/lcov-report/src/api/room/index.html
  coverage/lcov-report/src/api/room/index.ts.html
  coverage/lcov-report/src/api/room/room.controller.ts.html
  coverage/lcov-report/src/api/room/room.service.ts.html
  coverage/lcov-report/src/api/user/index.html
  coverage/lcov-report/src/api/user/index.ts.html
  coverage/lcov-report/src/api/user/user.controller.ts.html
  coverage/lcov-report/src/api/user/user.service.ts.html
  coverage/lcov-report/src/auth/auth.controller.ts.html
  coverage/lcov-report/src/auth/auth.service.ts.html
  coverage/lcov-report/src/auth/index.html
  coverage/lcov-report/src/auth/local/index.html
  coverage/lcov-report/src/auth/local/index.ts.html
  coverage/lcov-report/src/auth/local/local.controller.ts.html
  coverage/lcov-report/src/auth/utils/bcrypt.ts.html
  coverage/lcov-report/src/auth/utils/index.html
  coverage/lcov-report/src/config/app.ts.html
  coverage/lcov-report/src/config/express.ts.html
  coverage/lcov-report/src/config/index.html
  coverage/lcov-report/src/index.html
  coverage/lcov-report/src/routes.ts.html
  coverage/lcov.info
  prisma/migrations/20230629161002_db_update/migration.sql
Labels: large, waiting-for-review

#56 Delete pull_request_template .md
  .github/pull_request_template .md
Labels: small, waiting-for-review

#57 feat: user role
  src/api/user/index.ts
  src/api/user/user.service.ts
Labels: small, waiting-for-review
